[package]
name = "spirv-linker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspirv = "0.11"
thiserror = "1"
topological-sort = "0.1"