pre-release-commit-message = "Release {{version}}"
tag-message = "Release {{version}}"
tag-name = "{{version}}"
sign-commit = true
sign-tag = true

pre-release-replacements = [
  {file="README.md", search="spirv-linker = .*", replace="{{crate_name}} = \"{{version}}\""},
]